.\" Manpage for deck
.\" Contact marce@dziban.net to correct errors or typos
.TH man 1 "29 March 2018" "0.1" "deck man page"
.SH NAME
deck \- manage projects with ease
.SH SYNOPSIS
deck <command>  [<args>]
.SH DESCRIPTION
deck is a project manager with support for templates, tagging and recreation of the whole workspace from a single file
.SH AUTHOR
Marce Coll <marce@dziban.net>
